[project]
name = "pipefit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = []

[project.scripts]
pipefit = "pipefit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
